;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Dragon",NewTagName="Species")
+GameplayTagRedirects=(OldTagName="Species.Tree.Oak",NewTagName="Species.Plant.Oak")
+GameplayTagRedirects=(OldTagName="Species.Tree",NewTagName="Species.Plant")
+GameplayTagRedirects=(OldTagName="Species.Plant.Oak",NewTagName="Species.Plant.Tree")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Rarity",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Common",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Legendary",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Mythical",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Rare",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Uncommon",DevComment="")
+GameplayTagList=(Tag="Item.Type",DevComment="")
+GameplayTagList=(Tag="Item.Type.Biological",DevComment="")
+GameplayTagList=(Tag="Species",DevComment="")
+GameplayTagList=(Tag="Species.Dragon",DevComment="")
+GameplayTagList=(Tag="Species.Dragon.Bronze",DevComment="")
+GameplayTagList=(Tag="Species.Dragon.Gold",DevComment="")
+GameplayTagList=(Tag="Species.Dragon.Silver",DevComment="")
+GameplayTagList=(Tag="Species.Mammal",DevComment="")
+GameplayTagList=(Tag="Species.Plant.Tree",DevComment="")
+GameplayTagList=(Tag="Species.Plant.Tree.Oak",DevComment="")

